### ISSUE TITLE
Import time entries

### ISSUE THREAD

**Issue by gises** [Keleo/kimai2-grandtotal#1]
When importing the data into GrandTotal, please do not consider the already exported data records from Kimai. It would also be very helpful if, after invoicing the data in Grand Total, the data records in Kimai were marked as "exported/allocated". This plugin would be a great addition to the existing billing functions in Kimai.

**Comment by kevinpapst** [comment]
That is currently AFAIK impossible, as GrandTotal would need to inform the plugin about the items that were imported.
Please contact the GrandTotal developer to ask about it.
