### ISSUE TITLE
Support Kimai Version 1.10

### ISSUE THREAD

**Issue by gises** [Keleo/kimai2-grandtotal#3]
When starting the plugin in Grandtotal, a message appears that the plugin requires version 1.6 or higher. I am running Kimai version 1.10 and probably the version counter is not up to date.

Thanks for the customization

**Comment by kevinpapst** [comment]
Already fixed by @kulturbande - I just forgot to create a new release. Wait ...

**Comment by kevinpapst** [comment]
Can you please test the updated release: https://github.com/Keleo/kimai2-grandtotal/blob/master/Kimai2.grandtotalplugin.zip

**Comment by gises** [comment]
Hi Kevin

 

Just installed it and it works again. Sovled my problem.

Great support, Thanks!!!

Regards Michael

 

Von: Kevin Papst <notifications@github.com>
Antworten an: Keleo/kimai2-grandtotal <reply@reply.github.com>
Datum: Montag, 14. September 2020 um 21:39
An: Keleo/kimai2-grandtotal <kimai2-grandtotal@noreply.github.com>
Cc: GIM <giesingerm@gmail.com>, Author <author@noreply.github.com>
Betreff: Re: [Keleo/kimai2-grandtotal] Support Kimai Version 1.10 (#3)

 

Can you please test the updated release: https://github.com/Keleo/kimai2-grandtotal/blob/master/Kimai2.grandtotalplugin.zip

**Comment by kevinpapst** [comment]
thanks for testing, created release 1.1: 
https://github.com/Keleo/kimai2-grandtotal/releases/tag/1.1
