### ISSUE TITLE
Error logging in PHP8.1

### ISSUE THREAD

**Issue by bernd-bechermann** [Keleo/kimai2-grandtotal#8]
Hello. Preparing for Kimai 2.0 I switched my Server to PHP 8.1. In GrandTotal 7 this now gives me a Login Error for the Plugin. As soon as I switch back to 8.0 I can login to the Plugin again. Kimai Doctor shows no missing PHP extensions or other errors with PHP8.1.
Thank you/ Danke for your software!

**Comment by kevinpapst** [comment]
Works for me:
<img width="1245" alt="Bildschirm­foto 2023-01-13 um 11 46 24" src="https://user-images.githubusercontent.com/533162/212301935-35a5dad9-9ca7-4893-8bad-436d22f20bde.png">

**Comment by bernd-bechermann** [comment]
Thank you. It seems to be a problem with All Inkl (I should have mentioned the provider) and it's version pf PHP 8.1. As soon as I switch from 8.0 to 8.1 I get »The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.«-Errors on some – not all – pages in the Kimai backend. Even with fresh installs of either 1.30.3 or 2.0-Beta. So this was not a problem with this plugin at all. Sorry.

**Comment by kevinpapst** [comment]
Ah, All-Inkl again. You can search for "ioncubeLoader" - unfortunately a known issue.

I don't know how many people had that problems with 8.1 by now. Many...
All you can do is: write to the All-Inkl Support. If enough people complain about ioncubeLoader extension, while nobody really uses it, something might move on their end.

Second option: 
Stay on PHP 8.0 😢
